# Claude Code Orchestrator Configuration
# TeleVantage Churn Intelligence Platform

# Orchestrator settings
orchestrator:
  state_file: ".claude/orchestrator_state.json"
  log_level: info
  max_parallel_agents: 1  # Sequential execution
  timeout_minutes: 30
  execution_mode: in_session  # In-session guided execution
  busy_blocking: true

  retry:
    retries: 2
    backoff: 2.0
    jitter: 0.25
    retryable_exit_codes: [75, 101]
    retryable_messages:
      - "rate limit"
      - "transient network"

  # Handoff configuration
  handoff:
    include_full_context: true
    artifact_format: markdown
    preserve_history: true

# Subagent definitions
subagents:
  architect:
    enabled: true
    prompt_template: .claude/subagent_prompts/architect.md
    checkpoint_artifacts:
      - docs/architecture.md
      - docs/technical_spec.md
      - docs/design_system.md
      - docs/component_hierarchy.md

  data:
    enabled: true
    prompt_template: .claude/subagent_prompts/data.md
    checkpoint_artifacts:
      - src/data/**/*.json
      - docs/data_generation.md
      - scripts/generate_demo_data.py

  developer:
    enabled: true
    prompt_template: .claude/subagent_prompts/developer.md
    checkpoint_artifacts:
      - src/**/*
      - public/**/*
      - package.json
      - vite.config.ts
      - tailwind.config.js
      - tsconfig.json
      - index.html
      - docs/implementation_notes.md

  qa:
    enabled: true
    prompt_template: .claude/subagent_prompts/qa.md
    checkpoint_artifacts:
      - docs/test_plan.md
      - docs/test_results.md
      - docs/qa_report.md
      - tests/**/*

  documentarian:
    enabled: true
    prompt_template: .claude/subagent_prompts/documentarian.md
    checkpoint_artifacts:
      - README.md
      - docs/DEMO_SCRIPT.md
      - docs/DESIGN_SYSTEM.md
      - docs/DEPLOYMENT.md
      - docs/FAQ.md

  consensus:
    enabled: true
    prompt_template: .claude/subagent_prompts/consensus.md
    checkpoint_artifacts:
      - .claude/decisions/consensus_decisions.md
      - .claude/decisions/checkpoint_approvals.md

  reviewer:
    enabled: false  # Optional agent
    prompt_template: .claude/subagent_prompts/reviewer.md
    checkpoint_artifacts:
      - docs/code_review.md
      - docs/improvements.md

# Workflow configuration
workflow:
  phases:
    planning:
      agents: [architect]
      requires_consensus: true
      enabled: true
      description: "Design system architecture, component hierarchy, and design system"

    data_engineering:
      agents: [data]
      requires_consensus: false
      enabled: true
      description: "Generate scaled demo data from telco-churn_v2 results"
      artifacts_required:
        - src/data/**/*.json
        - docs/data_generation.md

    development:
      agents: [developer]
      requires_consensus: false
      enabled: true
      description: "Implement React application with 5 tabs and 7+ D3.js charts"
      artifacts_required:
        - src/**/*
        - package.json
        - vite.config.ts

    quality_assurance:
      agents: [qa]
      requires_consensus: true
      enabled: true
      description: "Test functionality, design compliance, and performance"
      artifacts_required:
        - docs/test_plan.md
        - docs/test_results.md
        - docs/qa_report.md

    documentation:
      agents: [documentarian]
      requires_consensus: false
      enabled: true
      description: "Create demo script, deployment guide, and executive materials"
      artifacts_required:
        - README.md
        - docs/DEMO_SCRIPT.md

    review:
      agents: [reviewer]
      requires_consensus: true
      enabled: false
      optional: true

  # Phase transition rules
  transitions:
    auto_advance: false  # Require explicit orchestrator approval
    rollback_enabled: true
    max_iterations: 3  # Maximum iterations per phase before escalation

# Checkpoint policy
checkpointPolicy:
  enabled: true
  storage_path: .claude/checkpoints/
  versioning: true
  retention_policy:
    keep_all_approved: true
    keep_last_n_rejected: 5

  validation:
    require_consensus_approval: true
    require_all_artifacts: true
    allow_partial_checkpoints: false

# Integration settings
integrations:
  git:
    auto_commit_checkpoints: false
    branch_per_phase: false

  notifications:
    enabled: false
    channels: []

# Project-specific settings
project:
  type: webapp
  framework: react
  language: typescript
  build_tool: vite

  source_data:
    path: /Users/pfay01/Projects/telco-churn_v2
    scale_factor: 6714
    base_customers: 7044
    target_customers: 47300000
